### ISSUE TITLE
AttributeError("module 'networkx' has no attribute 'connected_component_subgraphs'",)

### ISSUE THREAD

**Issue by janpisl** [AfriGIS-South-Africa/disconnected-islands#10]
The title is an error message received when trying to run the plugin in QGIS 3.10. The reason is that connected_component_subgraphs has been removed in networkx version 2.4

**Comment by petersmythe** [comment]
Thank you janpisl for your PR  https://github.com/AfriGIS-South-Africa/disconnected-islands/pull/9 which has been gratefully accepted.
