### ISSUE TITLE
networkx depreciated attribute 'connected_component_subgraphs'

### ISSUE THREAD

**Issue by wmeinolf** [AfriGIS-South-Africa/disconnected-islands#12]
As I closed the other case, I like to open a seperate one for thte depreciated Networks Attribute

2020-08-31T14:22:01 CRITICAL Error : Exception caught: AttributeError("module 'networkx' has no attribute 'connected_component_subgraphs'"). Please report an issue to the author of the plugin.

Obviously networkx depreciated the attribute a while ago and it was finally removed in version 2.4.
Wit Infomations form here: https://networkx.github.io/documentation/networkx-2.1/reference/algorithms/generated/networkx.algorithms.components.connected_component_subgraphs.html and here: https://stackoverflow.com/questions/61154740/attributeerror-module-networkx-has-no-attribute-connected-component-subgraph 

**Solution:** 
Modify disconnected_islands.py from: 
line 317: connected_components = list(nx.connected_component_subgraphs(G))

to: 
line 317: connected_components = list(G.subgraph(c) for c in nx.connected_components(G))

Best regards from Bavaria!

**Comment by petersmythe** [comment]
Danke schoen, wmeinolf.  I appreciate you taking the time to provide a solution arising from the new version of NetworkX.  It has been implemented in https://github.com/AfriGIS-South-Africa/disconnected-islands/releases/tag/v2.0.2
