### ISSUE TITLE
NetworkX is broken in Python3.9

### ISSUE THREAD

**Issue by cliffordsnow** [AfriGIS-South-Africa/disconnected-islands#13]
Disconnect-islands does not load because of a python error. The error message "CRITICAL    Error in plugin disconnected-islands : NetworkX module is required and missing. Please install it manually by executing, in a Terminal: sudo easy_install networkx. Then restart QGIS."

Even though the NetworkX module is installed, it errors our with a message "ImportError: cannot import name 'gcd' from 'fractions' (/usr/lib64/python3.9/fractions.py)" when it attempts to load the Networkx module. From what I understand, the math.gcd() function was changed in 3.9.

**Comment by tirkarthi** [comment]
This seems to have been fixed in networkx : https://github.com/networkx/networkx/pull/2861
