### ISSUE TITLE
error running on postGIS layer

### ISSUE THREAD

**Issue by guillermodangelo** [AfriGIS-South-Africa/disconnected-islands#3]
While trying to run your plugin in a PostGIS layer I've got this error, probably because the plugin does not set a field type (probably "bigint" would be the appropriate).
QGIS 3.4.0-Madeira, PostGIS 2.2.5
PostgreSQL 9.5.6 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11), 64-bit

This is the error output:
2018-12-04T09:18:34     CRITICAL    Capa ejes_osm_noded : Error de PostGIS al añadir atributos: ERROR: syntax error at end of input
             LINE 1: ALTER TABLE "ruteo"."ejes_osm_noded" ADD COLUMN "grupo" 
              ^
2018-12-04T09:18:34     CRITICAL    Error : Failed to create attribute!

**Comment by petersmythe** [comment]
Thanks for reporting the issue @guillermodangelo. It was designed to work with shape files (so try exporting some of your data to SHP, if you can), but I will take a look at extending it to work on PostGIS layers too.

**Comment by guillermodangelo** [comment]
Thanks, it worked well using a GeoPackage exported from the PostGIS DB.
