### ISSUE TITLE
Metadata mentions .qgis2 folder

### ISSUE THREAD

**Issue by DelazJ** [AfriGIS-South-Africa/disconnected-islands#4]
In the description of the plugin in Plugin Manager, some test data are supposed to be found in .qgis2 folder that should not be available,

**Comment by petersmythe** [comment]
Thanks @DelazJ.  Fixed in https://github.com/AfriGIS-South-Africa/disconnected-islands/commit/14d92230daf2babac93b93fbcff85ccdc6103632
