### ISSUE TITLE
Broken bug tracker link

### ISSUE THREAD

**Issue by DelazJ** [AfriGIS-South-Africa/disconnected-islands#5]
The bug tracker link in metadata still points to the unavailable https://issues.qgis.org/projects/disconnected-islands page instead of using the current github page

**Comment by petersmythe** [comment]
Thanks @DelazJ.  Fixed in https://github.com/AfriGIS-South-Africa/disconnected-islands/commit/14d92230daf2babac93b93fbcff85ccdc6103632
